apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgBRCTgtRIgPtG/sNw9H7k+UmlNJeiFt7GFFZ22fGKe7mY8b3ls3UhnZXzdwaRigDA6PKxM5REnEekBsgLJe/seoqq0dqdZq70iRQdpognoLe8QduDdugOopYTXe3h2PUo2P2ewEoGTHomVEfBSNnSAVf647PJrifGuLVoZbXM1QG0OQ9gKSu4MzCtqOBzPIWukvxnUbvjsXo7EPj31X0lt8JjknpOH8R6KPEfQlZGpoBBtALFjpCQfz9p43gcf1inxEcYqODG2B+icUO7wce1XVEZwTvn92tyy0i1UMC1vmWDt/tAn1o8IkJrL1hkic9NCWNU0gVWvOrXpWxLi/4pHQTdLIZkuJuQJeG5aH5PZTLKQupCyd+RgOj+weMrK245aOWQJmYSZ4RQcDwx7H0AAJ6mY8e4ynKI80GEavWvSTBnJxi55/mhbSfoLc6NunbKxz2piT3hAOJsj9e+XR7z0I46yc+DxmIz3yhmdSYzg1D+iuTLDUm77V8lzciXuCVjgWGRHCY3iwtaqr1VVDnYPiNxpsxaQ7yA4vwTxmR/7TK5B4rR+nM9i9D6VyJ4/04pH/zLejs47eQpDOAWTCUlkIYo0bzMvPqL7CE3vcyE0oP08NuFJB28FPwratF/6jV8bYdziExYNAd4tWhCDXNqUph4oJl3nnzs/LIEb79jppqo6TKNr0YX8Cohw3F60sxJo8t/cqyb061dvN9mXO8EpXIv6v+xH66ZYIFmOo1zoXvls/uIuLehse
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

