apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgB7UthgDF0WNhrffwiJ/8y3N9ewaqFLT6QuCREiTCNOTgBxI8kPOCbL1XUxFnL1t2Bco78VUM9cCQdutkqxm3NGQRvsIckkxauM/stSZfZtlV4frS1M4zSkpHbRHJV/9TVN6ddjZzEF/XpTp6n7ogRZs4T9xvchwcRbXXTRN7BTIsfaoYzqIANSxjjc+IzL/4XjKawcZmPkQ5BpDypusmpOrh9xGATRvsDVUsRYbOOw+5iFCk4dhX4Y0RoE9/TQk3svyxqUizNre59IT9gwr7TqNOlkcZbmQywrK4kTRVALwm3KSuFO0xRhOCDrZoMLujKLD1t+SPhFTbChIVXE2+3gfOUTqJVmXQlPxZ2tyguH86cpDbpVRUGGakh/p9Tnp8B5CAF16wYOc4hSQUqwch4n19H3aoQk7JhsJ/NTToVisHCv2VHLAOlBAUaYKUvr5iXAGcrvQzGDHBVsXiJ90fgUZJhsKqNViSA0KTzi8Swww+dsfppXhrRLNTMc5i2+0leG3ENfvYQrTKhD+warBnle0hGm+PwR/Esb7hlfi0Pet1deyaOxlUZYsA1R7HJcLm7IPBoZxACXitOV1VOUoQhFQsLi7HFKrqRYpoYTzeU6iKVpk1I/RclbROiKi5UeruA1pJdD3m5UB/ZU1Cdiycy3ifNG8kxV+TK9ZwEmu9UGrq9fNkC6Hbv0hb3TyvqoQFTq3LdeBxPjZO6RLixnVn/XI57o+a1XqztS+o3hXbdij0WpSudRfI9wU9K7Prz3UgKbqlQ31fX/3ATTkEN2K30rIjv5Gm9epd6Uik4lOIOkvvA6Ev5vK3C0XMRprmIj6XZO9qObyu8eL0IrM66OX7Jxvio6muvqUksld8pc7pDEVb3QkWWSlS/2hRRULdlXcK1LPgumED6Kv3geSLNlnduW1Iu0+XayrzvSOlMFHzoYOyYbsSbfCHZgsINAeyPPbxWUeJW9jSZYdKFC3NhCj9/eTY58RYQWeEMB2mQU9gNvPTTfaLKZPAtvYWSYyDn/MD1IY1PVCPrQmwBKLe5HLFfTAQ90wL4PucqO7OaNOljnftkmVaNvkRrvzedt4/uFOYQb9AmWoMZ5u5LptefynC6cMFkmBHv1Svyrj0emyOZRAzUN7E6+HtAavXMdicNXo0UXtY+RSlbj+711VLzjNQu3Buk5r8RLsFC4O37ssITLyzvdYxeM1bSuGcQSMW5jYIqWb+NwjhYDT+HabtFLgLBaIi2ggIqs5dydtx4nuP/m+EDtNTx17b8wB5cfXyJgNYbXfOh2FOp/jkc/MaCLEsB0B3UZj2g6dAA7IYiccP/SYPIiJrjpFn75sCJqOveCydVi
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

